# Add this to your existing netlify.toml file

# Edge Function for Perplexity API
[[edge_functions]]
  path = "/api/perplexity"
  function = "perplexity"

# Add this redirect for Perplexity API
[[redirects]]
  from = "/api/perplexity"
  to = "/.netlify/edge-functions/perplexity"
  status = 200
